#!/bin/bash -eu

if [[ -e BuildTools.jar ]]; then
  echo 'BuildTools.jar already exists. Skip download.'
else
  echo 'Download build tool'
  curl -O 'https://hub.spigotmc.org/jenkins/job/BuildTools/59/artifact/target/BuildTools.jar'
fi
echo 'Build Sipgot'
echo 'eula=true' > eula.txt
./start.sh
